hystrix:
  command:
    product-catalog-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

    order -management-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000